config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "pages#index"
    get "/signup", to: "users#new"
    get "/recruitment", to: "trainer_candidates#index"
    post "/signup", to: "users#create"
    get "/login", to: "jwt#new"
    post "/login", to: "jwt#create"
    delete "/logout", to: "users#destroy"
    post "/test_results", to: "test_results#create"

    resources :shops, only: %i(index show)
    resources :carts, only: %i(index destroy)
    resources :trainer_candidates, only: %i(index)
    resources :users, only: %i(new create show destroy)
    resources :purchased_courses, only: %i(index create show destroy)

    resources :courses, only: %i(show) do
      resources :lessons, only: %i(index new create)
      resources :trainer_candidates, only: %i(new create)
      resources :carts, only: %i(create)
    end
    resources :lessons, only: %i(show) do
      resources :questions, only: %i(new create destroy)
    end
    
    namespace :admin do
      resources :courses, except: %i(edit)
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, ->{where is_correct: true}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :course_tags, dependent: :destroy
  has_many :tags, through: :course_tags
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :purchased_courses, class_name: PurchasedCourse.name,
    foreign_key: :course_id, dependent: :destroy
  has_many :tags, through: :course_tags
  has_many :trainer_candidates, dependent: :destroy
  belongs_to :trainer, class_name: User.name,
    foreign_key: :user_id, optional: true
  has_many :users, through: :purchased_courses, dependent: :destroy

  validates :course_status, presence: true
  validates :description, length: {maximum: Settings.text_max}
  validates :name, presence: true, length: {maximum: Settings.string_max},
    uniqueness: {case_sensitive: true}

  enum course_status: {recruiting: 0, building: 1, complete: 2}

  scope :course_in_recruitment, ->{where course_status: :recruiting}
end

app/models/course_tag.rb
class CourseTag < ApplicationRecord
  belongs_to :course
  belongs_to :tag
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_one :test
  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, presence: true, length: {maximum: Settings.string_max},
    uniqueness: {case_sensitive: true}
  validates :video_url, presence: true, length: {maximum: Settings.string_max}

  scope :lessons_sort, ->{order created_at: :desc}
end

app/models/purchased_course.rb
class PurchasedCourse < ApplicationRecord
  belongs_to :course
  belongs_to :user

  validates_uniqueness_of :user_id, scope: %i(course_id)
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :test_questions, dependent: :destroy
  has_many :test, through: :test_questions
  has_many :user_answers, dependent: :destroy
  belongs_to :trainer, class_name: User.name, foreign_key: :user_id,
    optional: true
  accepts_nested_attributes_for :answers

  scope :questions_sort, ->{order created_at: :desc}
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :course_tags, dependent: :destroy
  has_many :courses, through: :course_tags
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :lesson
  has_many :test_result, dependent: :destroy
  has_many :test_questions, dependent: :destroy
  has_many :questions, through: :test_questions
end

app/models/test_question.rb
class TestQuestion < ApplicationRecord
  belongs_to :question
  belongs_to :test
end

app/models/test_result.rb
class TestResult < ApplicationRecord
  has_many :user_answers
  belongs_to :test, dependent: :destroy
  belongs_to :user, dependent: :destroy
end

app/models/trainer_candidate.rb
class TrainerCandidate < ApplicationRecord
  belongs_to :course
  belongs_to :user

  validates :introduce, presence: true, length: {maximum: Settings.max_email}
  validates :cv_url, presence: true, length: {maximum: Settings.max_email}
  validates_uniqueness_of :user_id, scope: %i(course_id)
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :purchased_courses, class_name: PurchasedCourse.name,
    foreign_key: :user_id, dependent: :destroy
  has_many :courses, through: :purchased_courses
  has_many :questions
  has_many :trainer_courses, class_name: Course.name, foreign_key: :user_id
  has_many :test_result, dependent: :destroy
  has_many :trainer_candidates, dependent: :destroy
  enum user_type: {trainee: 0, trainer: 1, admin: 2}

  before_save :email_downcase

  validates :email, presence: true, format: {with: URI::MailTo::EMAIL_REGEXP},
    length: {maximum: Settings.max_email}, uniqueness: {case_sensitive: false}
  validates :first_name, presence: true,
    length: {maximum: Settings.max_first_name}
  validates :last_name, presence: true,
    length: {maximum: Settings.max_last_name}
  validates :password, allow_nil: true,
    length: {minimum: Settings.min_password, maximum: Settings.max_password}

  scope :trainer_list, ->{where user_type: :trainer}

  has_secure_password

  def current_user? user
    self == user
  end

  private

  def email_downcase
    email.downcase!
  end
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :question
  belongs_to :test_result
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :refresh_cart, only: %i(index)

  def index; end

  def create
    add_product params[:course_id]
    redirect_to carts_path
  end

  def destroy
    remove_product params[:id]
    refresh_cart
    execute_ajax
  end

  private

  def refresh_cart
    add_product params[:id] unless session[:cart]
    @cart = Array.new
    session[:cart].each do |product|
      @cart << Course.find_by(id: product) if product
    end
    @cart = @cart.uniq
  end

  def add_product id
    session[:cart] ||= Array.new
    session[:cart] << id
  end

  def remove_product product
    session[:cart].delete_if{|f| f == product}
  end

  def execute_ajax
    respond_to do |format|
      format.html{redirect_to shop_carts_path}
      format.js
    end
  end
end

app/controllers/jwt_controller.rb
class JwtController < ApplicationController
  before_action :check_login, only: :new

  def new; end

  def create
    user = User.find_by email: login_params[:email].downcase
    remember_me = login_params[:remember_me]

    if user && user.authenticate(login_params[:password])
      login user, remember_me
      flash[:success] = t ".login_success"
      redirect_to user
    else
      flash.now[:danger] = t ".login_fail"
      render :new
    end
  end

  private

  def login_params
    params.require(:login).permit :email, :password, :remember_me
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @courses = Course.limit Settings.limit
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :check_course, only: :show

  def index
    @courses = Course.page(params[:page]).per Settings.limit
  end

  def show; end

  private

  def check_course
    @course = Course.find_by id: params[:id]

    return if @course.present?
    flash[:danger] = t ".dont_have_this_course"
    redirect_to shops_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
  def change_currency_on locale, cash
    return t :free unless cash.present?
    locale == Settings.en ? convert_to_american(cash) : convert_to_vietnam(cash)
  end

  def total_cost_of locale, cart
    total_cost = 0
    cart.each{|product| total_cost += product.price.to_i}
    change_currency_on locale, total_cost
  end

  private

  def convert_to_american cash
    number_to_currency cash
  end

  def convert_to_vietnam cash
    cash = cash.to_i
    number_to_currency cash * Settings.currency
  end
end

app/views/carts/_cart.html.erb
<% if @cart.present? %>
  <% @cart.each do |course| %>
    <div class="row">
      <div class="col-12 col-sm-12 col-md-2 text-center">
        <%= link_to shop_path course do %>
          <% image_tag "b1", class: "img-course" %>
        <% end %>
      </div>
      <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
        <h4 class="product-name">
          <strong>
            <%= truncate course.name, length: Settings.trcate_text %>
          </strong>
        </h4>
        <h4>
          <small><%= truncate course.description,
            length: Settings.des_max %></small>
        </h4>
      </div>
      <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
        <div class="col-3 col-sm-3 text-md-right"></div>
        <div class="col-4 col-sm-4 col-md-10 cost">
          <h6>
            <strong>
              <%= change_currency_on params[:locale], course.price %> 
              <i class="fa fa-tags"></i>
            </strong>
          </h6>
        </div>
        <div class="col-2 col-sm-2 col-md-2 text-right">
        <%= link_to cart_path(course),
          method: :delete, remote: true,
          class: "btn btn-outline-danger btn-xs" do %>
          <i class="fa fa-trash" aria-hidden="true"></i>
        <% end %>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
<% else %>
  <%= t ".you_dont_have_any_course" %>
<% end %>

app/views/carts/_total_cost.html.erb
<b><%= t ".total_price" %>: <b><%= total_cost_of params[:locale], @cart %></b>

app/views/carts/destroy.js.erb
$("#carts").html("<%= j render "carts/cart" %>");
$("#total").html("<%= j render "carts/total_cost" %>");

app/views/carts/index.html.erb
<div class="container">
  <div class="card shopping-cart">
    <div class="card-header bg-dark text-light">
      <i class="fa fa-shopping-cart" aria-hidden="true"></i>
      <%= t ".shipping_cart" %>
      <%= link_to t(".continue_shoping"), shops_path,
        class: "btn btn-outline-info btn-sm pull-right" %>
      <div class="clearfix"></div>
    </div>
      <div class="card-body">
        <div id="carts"><%= render "carts/cart" %></div>
      </div>
      <div class="card-footer">
        <div class="pull-right footer-custom">
          <%= link_to t(".checkout"), purchased_courses_path, method: :post,
            class: "btn btn-danger pull-right" %>
          <div class="pull-right total">
            <div id="total"><%= render "carts/total_cost" %></div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/jwt/new.html.erb
<% provide :title, t(".login") %>
<div class="container">
  <div class="col-lg-4 col-md-6 search-course-right signup-form">
    <%= form_with scope: :login, url: login_path,
      local: true, class: "form-wrap" do |l| %>
      <%= l.text_field :email, class: "form-control",
        placeholder: t(".email_address") %>
      <%= l.password_field :password, class: "form-control",
        placeholder: t(".password") %>
      <%= l.label :remember_me, class: "checkbox inline" do %>
        <%= l.check_box :remember_me %>
        <span><%= t ".remember_me" %></span>
      <% end %><br>
      <%= l.submit t(".login"), class: "primary-btn text-uppercase" %>
    <% end %>
  </div>
</div>