config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "pages#index"
    get "/signup", to: "users#new"
    get "/recruitment", to: "trainer_candidates#index"
    post "/signup", to: "users#create"
    get "/login", to: "jwt#new"
    post "/login", to: "jwt#create"
    delete "/logout", to: "users#destroy"
    post "/test_results", to: "test_results#create"

    resources :shops, only: %i(index show)
    resources :carts, only: %i(index destroy)
    resources :trainer_candidates, only: %i(index)
    resources :users, only: %i(new create show destroy)
    resources :purchased_courses, only: %i(index create show destroy)

    resources :courses, only: %i(show) do
      resources :lessons, only: %i(index new create)
      resources :trainer_candidates, only: %i(new create)
      resources :carts, only: %i(create)
    end
    resources :lessons, only: %i(show) do
      resources :questions, only: %i(new create destroy)
    end
    
    namespace :admin do
      resources :courses, except: %i(edit)
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_one :test
  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, presence: true, length: {maximum: Settings.string_max},
    uniqueness: {case_sensitive: true}
  validates :video_url, presence: true, length: {maximum: Settings.string_max}

  scope :lessons_sort, ->{order created_at: :desc}
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :test_questions, dependent: :destroy
  has_many :test, through: :test_questions
  has_many :user_answers, dependent: :destroy
  belongs_to :trainer, class_name: User.name, foreign_key: :user_id,
    optional: true
  accepts_nested_attributes_for :answers

  scope :questions_sort, ->{order created_at: :desc}
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :search_course, only: %i(new create)
  before_action :list_lessons, only: %i(new)
  before_action :current_lesson, only: %i(show)

  def new
    @lessons = Lesson.new
  end

  def create
    @lesson = @course.lessons.build lesson_params

    if @lesson.save
      list_lessons
      respond_to do |format|
        format.html{redirect_to new_course_lesson_path @course}
        format.js
      end
    else
      flash.now[:danger] = t ".create_lesson_fail"
    end
  end

  def show
    @questions = @lesson.test.questions.includes :answers
  end

  private

  def lesson_params
    params.require(:lesson).permit :name, :video_url
  end

  def list_lessons
    @list_lessons = @course.lessons.lessons_sort
  end

  def search_course
    @course = Course.find_by id: params[:course_id]

    if @course
      return if current_user.current_user? @course.trainer
      flash[:danger] = t ".wrong_trainer"
    else
      flash[:danger] = t ".course_not_found"
    end
    redirect_to root_path
  end

  def current_lesson
    return if @lesson = Lesson.find_by(id: params[:id])
    flash[:danger] = t ".lesson_doesnt_exist"
    redirect_to root_path
  end
end

app/views/lessons/_lesson.html.erb
<div class="row lessons">
  <div class="col col-xl-4 col-lg-12 col-md-12 col-sm-12 col-12">
    <h6>
      <%= lesson.name %>
    <h6>
  </div>

  <div class="col col-xl-4 col-lg-12 col-md-12 col-sm-12 col-12">
    <h6>
      <%= lesson.video_url %>
    <h6>
  </div>

  <div class="col col-xl-4 col-lg-12 col-md-12 col-sm-12 col-12" >
    <%= link_to t(".edit"), "#",
      class: "text-uppercase genric-btn primary btn btn-default" %>
    <%= link_to t(".delete"), "#",
      class: "text-uppercase genric-btn primary btn btn-default" %>
    <%= link_to t(".write_test"), new_lesson_question_path(lesson),
      class: "text-uppercase genric-btn primary btn btn-default" %>
  </div>
</div>

app/views/lessons/_test_sheet.html.erb
<% if @questions %>
  <%= form_tag test_results_path id: @lesson.id do %>
    <% @questions.each do |question| %>
      <div class="question">
        <%= question.content %>
        <div class="answer">
        <% question.answers.each do |answer| %>
          <%= check_box_tag "answer_ids[]", answer.id %>
          <%= answer.content %><br>
        <% end %>
        </div>
      </div>
      <br>
    <% end %>
    <%= submit_tag t ".submit" %>
  <% end %>
<% else %>
  <%= t ".we_dont_have_any_questions_for_now" %>
<% end %>

app/views/lessons/create.js.erb
$("#show_lessons").html("<%=j render @list_lessons %>");

app/views/lessons/new.html.erb
<% provide :title, t(".add_course_lessons") %>
<div class="container">
  <div class="row">
    <div class="col-lg-12 left-contents" >
      <%= form_with model: [:course, @lessons] do |f| %>
        <div class="row">
          <div class="col col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <h3 class="h3-title">
              <%= t ".add_lessons_to_course" %>
            </h3>
          </div>

          <div class="col col-xl-4 col-lg-12 col-md-12 col-sm-12 col-12">
            <div>
              <%= f.label :name, t(".name") %>
              <%= f.text_field :name, class: "form-control",
                placeholder: t(".enter_lesson_name") %>
            </div>
          </div>

          <div class="col col-xl-4 col-lg-12 col-md-12 col-sm-12 col-12">
            <div>
              <%= f.label :video_url, t(".video_url") %>
              <%= f.text_field :video_url, class: "form-control",
                placeholder: t(".enter_video_url") %>
            </div>
          </div>

          <div class="col col-xl-4 col-lg-12 col-md-12 col-sm-12 col-12">

            <%= f.submit t(".add_lesson"),
              class: "text-uppercase genric-btn primary btn btn-default
              submit_button" %>
          </div>
        </div>
      <% end %>

      <div class="col col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <h3 class="h3-title">
          <%= t ".lessons_list" %>
        </h3>
      </div>
    </div>
  </div>

  <div id="show_lessons">
    <%= render @list_lessons %>
  </div>
</div>

app/views/lessons/show.html.erb
<% if @lesson %>
  <% provide :title, @lesson.name %>
  <h3><b><p><%= @lesson.name %></p></b></h3>
  <div><%= @lesson.video_url.html_safe %></div>
<% end %>
<br><br><br>
<%= render "lessons/test_sheet" %>