config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "pages#index"
    get "/signup", to: "users#new"
    get "/recruitment", to: "trainer_candidates#index"
    post "/signup", to: "users#create"
    get "/login", to: "jwt#new"
    post "/login", to: "jwt#create"
    delete "/logout", to: "users#destroy"
    post "/test_results", to: "test_results#create"

    resources :shops, only: %i(index show)
    resources :carts, only: %i(index destroy)
    resources :trainer_candidates, only: %i(index)
    resources :users, only: %i(new create show destroy)
    resources :purchased_courses, only: %i(index create show destroy)

    resources :courses, only: %i(show) do
      resources :lessons, only: %i(index new create)
      resources :trainer_candidates, only: %i(new create)
      resources :carts, only: %i(create)
    end
    resources :lessons, only: %i(show) do
      resources :questions, only: %i(new create destroy)
    end
    
    namespace :admin do
      resources :courses, except: %i(edit)
    end
  end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  before_action :check_admin
  before_action :list_courses, only: %i(index)
  before_action :data_list, only: %i(new)
  before_action :search_course, only: %i(show update destroy)
  before_action :list_candidates, only: %i(show)
  before_action :assign_user_as_trainer, only: %i(update)

  def index; end

  def new
    @course = Course.new
  end

  def create
    @course = Course.create course_params

    if @course.save
      tagging
      flash[:success] = t ".course_created"
      redirect_to admin_courses_path
    else
      flash.now[:danger] = t ".create_course_fail"
      data_list
      render :new
    end
  end

  def show; end

  def update
    if @course.update trainer: @user, course_status: :building
      flash[:success] = t ".assign_trainer_success"
      redirect_to admin_courses_path
    else
      flash[:danger] = t ".assign_trainer_failed"
      redirect_to admin_course_path @course
    end
  end

  def destroy
    @course.destroy
    list_courses
    respond_to do |format|
      format.html{redirect_to admin_courses_path}
      format.js
    end
  end

  private

  def course_params
    params.require(:course).permit :name, :course_status, :user_id, :price,
      :overview_video_url, :duration, :description, :employment_conditions
  end

  def data_list
    @list_status = Course.course_statuses
                         .map{|h, _| [I18n.t(Settings.course_i18n_path + h), h]}
    @list_trainer = User.trainer_list
                        .map{|p| [(p.first_name + " " + p.last_name), p.id]}
  end

  def tag_params
    params[:course][:tag]
  end

  def tagging
    tag_params.split(",").each do |tag|
      @tag = Tag.find_by name: tag
      if @tag
        assign_tag_to_course
      else
        @tag = Tag.new name: tag
        if @tag.save
          assign_tag_to_course
        else
          flash.now[:danger] = t(".create_tag_fail") + @tag.name
        end
      end
    end
  end

  def assign_tag_to_course
    @course_tag = @course.course_tags.build tag: @tag

    return if @course_tag.save
    flash[:danger] = t(".assign_tag_fail") + @tag.name
  end

  def list_courses
    @list_courses = Course.course_in_recruitment
  end

  def list_candidates
    @list_candidates = @course.trainer_candidates.includes :user
  end

  def search_course
    @course = Course.find_by id: params[:id]

    return if @course
    flash[:danger] = t ".course_not_found"
    redirect_to admin_courses_path
  end

  def assign_user_as_trainer
    @user = User.find_by id: params[:user_id]
    @user.trainer!

    return if @user.save
    flash[:danger] = t ".assign_trainer_fail"
    redirect_to admin_course_path @course
  end

  def check_admin
    return if current_user.admin?
    flash[:danger] = t ".not_admin"
    redirect_to root_path
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :check_user, :search_course, only: %i(show)

  def show; end

  private

  def search_course
    @course = Course.find_by id: params[:id]

    return search_lessons if @course
    flash[:danger] = t ".course_doesnt_exist_anymore"
    redirect_to purchased_courses_path
  end

  def search_lessons
    @list_lessons = @course.lessons
                           .page(params[:page]).per Settings.lessons_per_page
  end
end

app/views/courses/_course.html.erb
<div class="col-lg-6 pb-30">
  <div class="single-carusel row align-items-center">
    <div class="col-12 col-md-6 thumb">
      <%= image_tag "e1", class: "img-fluid" %>
    </div>
    <div class="details col-12 col-md-6">
      <%= link_to new_course_trainer_candidate_path(course.id) do %>
        <h4>
          <%= truncate course.name, length: Settings.trcate_name %>
        </h4>
      <% end %>
      <p>
        <%= truncate course.employment_conditions,
          length: Settings.text_length %>
      </p>
      <div class="text-uppercase genric-btn primary btn btn-default
        add_button">
        <%= link_to t(".apply"), new_course_trainer_candidate_path(course.id),
          class: "text_white" %>
      </div>
    </div>
  </div>
</div>

app/views/courses/_list_lessons.html.erb
<% if @list_lessons.present? %>
  <% @list_lessons.each do |lesson| %>
    <div class="row">
      <div class="col-12 col-sm-12 col-md-2 text-center"></div>
      <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
        <h4 class="product-name">
          <strong>
            <%= link_to lesson_path lesson do %>
              <%= truncate lesson.name,
                length: Settings.trcate_text %>
            <% end %>
          </strong>
        </h4>
      </div>
    </div>
    <hr>
  <% end %>
<% else %>
  <%= t ".dont_have_any_lesson" %>
<% end %>

app/views/courses/show.html.erb
<% provide :title, t(".lesson") %>

<% if @course.present? %>
  <div class="course-detail">
    <div class="course-name">
      <h3><b><p><%= @course.name %></p></b></h3>
      <br>
      <p><%= @course.description %></p>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="card shopping-cart">
    <div class="card-header bg-dark text-light">
      <div class="clearfix"></div>
    </div>
    <div class="card-body">
      <%= render "courses/list_lessons" %>
    </div>
  </div>
  <br>
  <div class="kaminari">
    <%= paginate @list_lessons, theme: "twitter-bootstrap-4" %>
  </div>
</div>